### ISSUE TITLE
Question about dataset

### ISSUE THREAD

**Issue by yxh02** [BryanPlummer/two_branch_networks#1]
Hi, your work is very great.
Can I use your work on my dataset?
If it is possible, how to do?
Looking forward for your answer.

**Comment by BryanPlummer** [comment]
Hi, thanks for your interest.  This repo is not actively maintained, but you are free to reuse it under the terms in the provided license.  To use other datasets typically you would have to alter it to fit the expected format of the code, i.e., it would need a new data loader like in dataset_utils.py
